name: clang-format

on: [push, pull_request]

permissions:
  contents: read

jobs:
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: npm install
      - name: check clang-format
        run: |
          git config clangFormat.binary node_modules/.bin/clang-format
          git config clangFormat.style file
          npx check-clang-format
