name: Test Website Builds

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test-website:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: npx envinfo
      - name: Build and Deploy
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        working-directory: ./website
        run: |
          npm install
          npx gatsby build --prefix-paths
